name: Build DKV Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  tinyphone_docker_job:
    name: Build DKV
    runs-on: windows-2016
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}
    - name: Set vars
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Build and Push DKV to registry
      run: |
        docker build --file=./Dockerfile -t ghcr.io/${{ github.repository_owner }}/dkv:latest -t ghcr.io/${{ github.repository_owner }}/dkv:${{ steps.vars.outputs.sha_short }} .
        docker push ghcr.io/${{ github.repository_owner }}/dkv:latest
        docker push ghcr.io/${{ github.repository_owner }}/dkv:${{ steps.vars.outputs.sha_short }}
